dbt_research:
  outputs:
    dev:
      database: "{{ env_var('AWS_DATABASE') }}"
      region_name: "{{ env_var('AWS_REGION') }}"
      s3_data_dir: "{{ env_var('AWS_S3_BUCKET') }}"
      s3_staging_dir: "{{ env_var('AWS_S3_STAGING_DIR') }}"
      schema: "{{ env_var('AWS_SCHEMA') }}"
      threads: 1
      type: "{{ env_var('DB_TYPE') }}"
  target: dev

